---
- hosts: app
  become: true
  tasks:
    - name: Deploy Student List webapp 
      docker_container:
        name: pozos-website
        hostname: pozos-website
        image: php:apache
        state: started
        ports:
          - "8080:8080"
...
