---
- hosts: app
  become: true
  tasks:
    - name: Deploy Student List webapp 
      docker_container:
        name: pozos-website-1.3
        hostname: pozos-website-1.3
        image: hzsupinfo/4devop-projet
        state: started
        ports:
          - "8080:8080"
    - name: Deploy POZOS API
      docker_container:
        name: pozos-api-1.3
        hostname: pozos-api-1.3 
        image: hzsupinfo/4devop-projet
        state: started
        links:  
          - pozos-website-1.3:pozos-website-1.3
        ports:
          - "80:80"
...
