---
- hosts: app
  become: true
  tasks:
    - name: Deploy Student List webapp 
      docker_container:
        name: pozos-website
        hostname: pozos-website
        image: hzsupinfo / projet-devop-zl:latest
        state: started
        ports:
          - "8002:80"
...
