---
- hosts: app
  become: true
  tasks:
    - name: Deploy Student List webapp 
      docker_container:
        name: pozos-website
        hostname: pozos-website
        image: php:apache
        state: started
        ports:
          - "8002:80"
      environnement: 
        USERNAME: "toto"
        PASSWORD: "python"
    - name: Deploy POZOS API
      docker_container:
        name: pozos-api
        hostname: pozos-api
        image: manumazu/api-pozos
        state: started
        ports:
          - "4000:5000"
...
